// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/verify-otp": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/activities": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/gift-types": {
    params: {};
  };
  "/group-calls": {
    params: {};
  };
  "/user-reports": {
    params: {};
  };
  "/verify-talent": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/verify-otp" | "/dashboard" | "/activities" | "/categories" | "/gift-types" | "/group-calls" | "/user-reports" | "/verify-talent";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/signin.tsx": {
    id: "routes/signin";
    page: "/signin";
  };
  "routes/verify-otp.tsx": {
    id: "routes/verify-otp";
    page: "/verify-otp";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/activities.tsx": {
    id: "routes/activities";
    page: "/activities";
  };
  "routes/categories.tsx": {
    id: "routes/categories";
    page: "/categories";
  };
  "routes/gift-types.tsx": {
    id: "routes/gift-types";
    page: "/gift-types";
  };
  "routes/group-calls.tsx": {
    id: "routes/group-calls";
    page: "/group-calls";
  };
  "routes/user-reports.tsx": {
    id: "routes/user-reports";
    page: "/user-reports";
  };
  "routes/verify-talent.tsx": {
    id: "routes/verify-talent";
    page: "/verify-talent";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/home": typeof import("./app/routes/home.js");
  "routes/signin": typeof import("./app/routes/signin.js");
  "routes/verify-otp": typeof import("./app/routes/verify-otp.js");
  "routes/dashboard": typeof import("./app/routes/dashboard.js");
  "routes/activities": typeof import("./app/routes/activities.js");
  "routes/categories": typeof import("./app/routes/categories.js");
  "routes/gift-types": typeof import("./app/routes/gift-types.js");
  "routes/group-calls": typeof import("./app/routes/group-calls.js");
  "routes/user-reports": typeof import("./app/routes/user-reports.js");
  "routes/verify-talent": typeof import("./app/routes/verify-talent.js");
};